name: Keep Render Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Zai riƙa duba shi duk bayan minti 5
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://mrou-topstudio-app.onrender.com/'
          method: 'GET'
